
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'YouGuo' do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'Kingfisher'
    pod 'HandyJSON'
    pod 'SnapKit'
    pod 'SVProgressHUD'
    pod 'PullToRefreshKit'
end
